services:
  - type: web
    name: bot-telegram
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn bot:app --bind 0.0.0.0:$PORT --workers 3 --worker-class gevent
    envVars:
      - key: TELEGRAM_TOKEN
        sync: false
      - key: OWNER_ID
        sync: false
      - key: GROUP_CHAT_ID
        sync: false
      - key: WEBHOOK_URL
        sync: false
      - key: ACCESS_PASSWORD
        sync: false
      - key: USE_WEBHOOK
        sync: false
      - key: PORT
        sync: false
