services:
  - type: web
    name: bot-telegram
    env: python
    plan: free
    buildCommand: ""
    startCommand: python bot.py
    envVars:
      - key: TELEGRAM_TOKEN
        sync: false
      - key: OWNER_ID
        sync: false
      - key: GROUP_CHAT_ID
        sync: false
      - key: WEBHOOK_URL
        sync: false
